repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
        args: ['--maxkb=123']
        exclude: >
          (?x)^(
              .pnp.cjs|
              package-lock.json|
              Pipfile.lock|
          )$
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-json
        exclude: ^.vscode/
      - id: check-xml
      - id: check-yaml
        exclude: >
          (?x)^(
              .gitlab-ci.yml|
          )$
      - id: check-symlinks
      - id: check-merge-conflict
      - id: debug-statements
      - id: detect-private-key
        exclude: >
          (?x)^(
              README.md|
          )$
      - id: double-quote-string-fixer
      - id: name-tests-test
      - id: end-of-file-fixer
      - id: fix-encoding-pragma
      - id: requirements-txt-fixer
      - id: sort-simple-yaml
      - id: file-contents-sorter
  - repo: https://github.com/pre-commit/pre-commit.git
    rev: v2.19.0
    hooks:
      - id: validate_manifest
  - repo: https://github.com/asottile/add-trailing-comma
    rev: v2.2.3
    hooks:
      - id: add-trailing-comma
  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.5.1-1
    hooks:
      # Choose one of:
      #- id: shfmt         # native (requires Go to build)
      - id: shfmt-docker  # Docker image (requires Docker to run)
  - repo: https://github.com/detailyang/pre-commit-shell
    rev: 1.0.5
    hooks:
      - id: shell-lint
        # entry: pre_commit_hooks/shell-lint.sh -x
        args: [-x]
        exclude: >
          (?x)^(
              test/.*|
          )$
  - repo: https://github.com/Lucas-C/pre-commit-hooks-nodejs
    rev: v1.1.2
    hooks:
      - id: htmlhint
        args: [--config, .htmlhintrc]
      - id: htmllint
      - id: markdown-toc
        args: [--maxdepth, "3", -i]
      # - id: dockerfile_lint
      #   args: [--json, --verbose, --dockerfile]
#  - repo: https://github.com/bridgecrewio/checkov.git
#    rev: '2.0.1159'
#    hooks:
#    - id: checkov
#      verbose: true
#      args: [--soft-fail]
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.8.7
    hooks:
#      - id: gitleaks
#        args: [--config, gitleaks.toml]
      - id: gitleaks-docker
        entry: zricethezav/gitleaks protect --verbose --redact --staged
        #entry: zricethezav/gitleaks detect --verbose
